name: mikan
description: mikanani.me

version: 1.3.1+84

publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.29.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6
  path_provider: ^2.1.5
  dio: ^5.7.0
  dio_cookie_manager: ^3.0.0
  html: ^0.15.4
  provider: ^6.1.2
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.0.0
  clipboard: ^3.0.8
  url_launcher: ^6.3.1
  share_plus: ^12.0.1
  flutter_widget_from_html_core: ^0.17.0
  extended_sliver: ^2.1.3
  waterfall_flow: ^3.0.2
  jiffy: ^6.4.4
  android_intent_plus: ^6.0.0
  connectivity_plus: ^7.0.0
  ff_annotation_route_core: ^2.1.1
  ff_annotation_route_library: ^3.2.3
  sliver_tools: ^0.2.12
  flutter_displaymode: ^0.7.0
  flex_color_picker: ^3.8.0
  intl: ^0.20.2
  collection: ^1.19.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  cookie_jar: ^4.0.2
  async: ^2.11.0
  auto_size_text: ^3.0.0
  easy_refresh: ^3.3.2+1
  window_manager: ^0.5.1
  dynamic_color: ^1.7.0
  decimal: ^3.2.0
  flutter_smart_dialog: ^4.9.8
  infinite_carousel: ^1.0.3
  package_info_plus: ^9.0.0
  animations: ^2.1.1
  vclibs: ^0.1.3
  in_app_update: ^4.2.5
  gap: ^3.0.1
  expressive_loading_indicator: ^0.0.1

dev_dependencies:
  args: ^2.4.1
  yaml: ^3.1.2
  glob: ^2.1.1
  http: ^1.6.0
  process_run: ^1.0.0+1
  build_runner: ^2.4.13
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  json_serializable: ^6.11.3
  hive_ce_generator: ^1.1.0
  flutter_lints: ^6.0.0
  quiver: ^3.2.1

dependency_overrides:
  collection: ^1.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/res/
  line_length: 80
  integrations:
    flutter_svg: true
    rive: true
    lottie: true

